### ISSUE TITLE
Error while installing python-vlc binding

### ISSUE THREAD

**Issue by Enadeia** [project-owner/Peppy.doc#1]
Hi,

I was looking for some informations about implementing a wired webradio project with my rasp Pi2, after some researches I was planning to buy an adafruit LCD touchscreen and hifiberryAMP+. While researching how to plug them all (it seems there could be GPIO conflicts issues) I ended up on your project and I thank you for sharing it an all the necessary documentation.

I followed all the steps until VLC installation and python-vlc binding cloning. When I got to the step:
sudo python setup.py install
It correctly started but ended with an error:
- 
![image](https://user-images.githubusercontent.com/32996556/31860994-4b979036-b724-11e7-9c11-629a46dedab2.png)

I can't understand this error as both folder and file seems to be correctly cloned:

- 
![image](https://user-images.githubusercontent.com/32996556/31860999-6b581706-b724-11e7-8340-676703a2681c.png)

I deleted the python-vlc folder and cloned it again but I had the same problem.

So I am totally lost ! Do you have an idea of what could cause this issue ?

Thanks a lot for you help !

**Comment by oaubert** [comment]
The structure of the python-vlc repository changed recently, to simplify some packaging issues. The Peppy documentation should be updated with something like the following:

The preferred way to install the python-vlc bindings is to use pip:
 
    pip install python-vlc

Alternatively, it can be installed from git using the following commands:

    git clone https://github.com/oaubert/python-vlc.git
    cd python-vlc/generated/2.2
    sudo python setup.py install

**Comment by Enadeia** [comment]
Great, it solved my problem.
Thanks a lot !

**Comment by project-owner** [comment]
Thanks a lot for helping out! Peppy wiki was modified accordingly.
