### ISSUE TITLE
Bluetooth not working.

### ISSUE THREAD

**Issue by AubreyKloppers** [project-owner/Peppy.doc#10]
Good morning.
When I try and start/enable Bluetooth, the UI hangs and the Bluetooth does not work.

I have tested this with the Buster Lite release, and this works.  I also tested this with the instructions as set out with the "[Expert](https://github.com/project-owner/Peppy.doc/wiki/Expert)" installation.  The moment these steps gets executed:
```
Peppy Player Installation
Install all required libraries which Peppy Player depends on:

sudo apt-get install eject
sudo apt-get install bluealsa
sudo apt-get install -y libasound2-plugin-equal
sudo apt-get install udisks2
pip3 install tornado
pip3 install RPi.GPIO
pip3 install discogs_client
pip3 install pynanosvg
pip3 install feedparser
pip3 install mutagen
pip3 install pexpect
pip3 install Pillow
pip3 install rpi-backlight
pip3 install pyudev
pip3 install pyowm
```
the  Bluetooth device stops working.

Kind regards
cyber7 (aka Aubrey Kloppers, Cape Town, South Africa)

**Comment by project-owner** [comment]
Hi Aubrey,

Which OS do you use for player installation? Is it Lite or Desktop version? Which Pi model do you use? Is it Pi 3 or Pi4?
Are you able to run manually the commands described on this page (pair, trust, connect):
https://github.com/project-owner/Peppy.doc/wiki/Bluetooth-Devices

There was similar report about a Bluetooth issue here: https://github.com/project-owner/Peppy/issues/12
Probably it's applicable in you case as well (?)

Best regards

**Comment by AubreyKloppers** [comment]
Hi Peppy-Owner
First of all, this "thing" of yours is amazing, but I am sure everybody tells you this!

Details 1:
1. I am using a Raspberry PI 4 4GB.
2. I use Waveshare 3.5B headless instructions. (https://github.com/project-owner/PeppyPlayers.doc/wiki/Waveshare-3.5-(B))
3. The moment I try to start the Bluetooth, the UI hangs. (Peppy, not the config)

Details 2:
1. I use the monet-waveshare.3.5.zip (https://github.com/project-owner/PeppyPlayers.doc/wiki/Disk-Images)
2. The moment I try to start the Bluetooth the UI hangs. (Peppy, not the config)

Details 3:
1. I run the expert instructions (https://github.com/project-owner/Peppy.doc/wiki/Expert)
2. Right through the instructions the Bluetooth works and I can list/pair.
3. The moment I do a : "sudo apt-get install bluealsa" the bluetooth stopps working...

Details 4:
(https://www.raspberrypi.org/forums/viewtopic.php?t=306699)
I change the file 
From:
console=ttyAMA0,115200
To:
console=serial0,115200

And it WORKED! 

Please mark as solved :)

Have a great day!
