### ISSUE TITLE
Alsa Lib Problems

### ISSUE THREAD

**Issue by Ravens62** [project-owner/Peppy.doc#11]
Hi,
I have a HiFiBerry AMP2 V1.1 card and does not work playback.
Either it sounds nothing or it is 100% and it is not possible to silit it ...
Hifiberry AMP2 v1.1, Raspberry 3B, Raspberry OS 32b r. 2021-05-07
![2021-07-16-090140_1824x984_scrot](https://user-images.githubusercontent.com/35656251/125992290-c6bc22fa-4d95-4137-b6c7-852cdc673414.png)
APLAY works normally, it is heard by volume setting level, but according to Peppy there is still a problem, see Screen.

**Comment by project-owner** [comment]
Hi, please make sure that you have these setting in the player configuration file /home/pi/Peppy/config.txt:
https://github.com/project-owner/Peppy/blob/c934ac87da3ae3f6b42079654692a50538c9faf0/config.txt#L159
```
[volume.control]
type = amixer
amixer.scale = linear
amixer.control = Digital
initial.volume.level = 
```

**Comment by project-owner** [comment]
Also, please show the output from the commands:
```
aplay -l
aplay -L
```
and screenshot after running the command:
```
alsamixer
```

**Comment by Ravens62** [comment]
Hi, I didn't change the change in Config, but didn't help.
![Screen config](https://user-images.githubusercontent.com/35656251/126028799-831e4171-802a-4a0f-bb71-0b67c730df68.png)
Before changing audiocarts:
![Screen Alsa před](https://user-images.githubusercontent.com/35656251/126028815-540f2fd4-627b-4542-926c-8c0256bbbda9.png)
After changing audiocarts:
![Screen Alsa po](https://user-images.githubusercontent.com/35656251/126028828-dde4c3f4-6029-4ac2-98e3-1c7ccb815f3c.png)
![Screen aplay](https://user-images.githubusercontent.com/35656251/126028840-9abd7f13-4e76-4951-a894-178f3cd708da.png)
Just the card is doing what he wants.

**Comment by project-owner** [comment]
You can try to set 'player' volume control:
```
[volume.control]
type = player
```

**Comment by Ravens62** [comment]
Hi, another mistake, no sound,
ALSA Lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM equal

**Comment by Ravens62** [comment]
Hi, helped edit .soundrc file:
pcm.plugequal {
  type equal;
  slave.pcm "plughw:0,0";
na:
pcm.plugequal {
  type equal;
  slave.pcm "plughw:0";

But when I stop the player incorrectly, you need to disconnect the voltage, so the .soundrc file will lose and again the same error .
ALSA Lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM equal

**Comment by project-owner** [comment]
Hi, sometimes after reboot ALSA can assign different card numbers. To handle that you can try to specify CARD and DEVICE this way in the file /home/pi/.asoundrc:
```
pcm.plugequal {
  type equal;
  slave.pcm "plughw:CARD=sndrpihifiberry,DEV=0";
}

```

**Comment by Ravens62** [comment]
Hi, so this solution works so far.
[volume.control]
type = player

pcm.plugequal {
  type equal;
  slave.pcm "plughw:CARD=sndrpihifiberry,DEV=0";
}

**Comment by project-owner** [comment]
OK, player type is a little bit slower than the amixer type.
Closing the issue as a have a workaround.
