### ISSUE TITLE
peppy not starting into UI

### ISSUE THREAD

**Issue by ftastisch** [project-owner/Peppy.doc#17]
Hi!

First if all big thank for the project and the extensive documentation.

I do have one issue after following the expert guide though: The interface does not show on the attached LCD, only in the Web UI.

I am using this screen: http://www.lcdwiki.com/3.5inch_RPi_Display
When I start peppy it just shows a pygame greeting and that's it. I can use peppy from the Web UI, but the screen stays black with the pygame greeting.

Any idea what that might be?

**Comment by ftastisch** [comment]
Hi,

Thanks, it helps at least partially. :D fbcp in /etc/rc.local was a very good advice. Now it shows the peppy screen.

Touch does not work yet however.
`sudo TSLIB_FBDEVICE=/dev/fb1 TSLIB_TSDEVICE=/dev/input/touchscreen ts_calibrate`
results in 
`ts_setup: No such file or directory`

I might this solution then, as the touchscreen was working under LXDE:
https://smarttechnotes.com/2020/08/21/raspberry-pi-touchscreen-internet-radio/

**Comment by project-owner** [comment]
Good progress! In that command try to to use fb0 instead of fb1 and see if it helps.

**Comment by ftastisch** [comment]
Unfortunately not, same error (ts_setup still does not exist ;)).

**Comment by project-owner** [comment]
Did you follow all steps and created this file: sudo nano /etc/udev/rules.d/95-ads7846.rules
and did this?
sudo apt-get install libts-bin
sudo reboot

**Comment by ftastisch** [comment]
> Did you follow all steps and created this file: sudo nano /etc/udev/rules.d/95-ads7846.rules and did this?
Yes, exactly. I just renamed the touchscreen to my model and driver. Changing it back it seems to make it work (was that really the problem?). Although touch is not working correctly. Meaning it reacts to touch, although not in the right places. I tried calibration, but the console turns black in that case and I do not see where to touch...

> sudo apt-get install libts-bin sudo reboot
Was already installed in newest version.

**Comment by project-owner** [comment]
Please read this post, maybe it will help: https://forums.raspberrypi.com/viewtopic.php?t=139983&start=275#p1906372
You need to make a successful calibration.

**Comment by ftastisch** [comment]
Playing around with it I just replaced fb1 with fb0 again and voilà, the markings for calibration appear.

I need to dig deeper into this however based on your links. While touch now basically works (I can press the screen and something happens), it is far from accurate. I don't really see a system correlating the point of touch to the registered touch. It might have to do with the fact that I rotated the display 180° before installing peppy, but not sure.

**Comment by project-owner** [comment]
The rotation can affect the calibration.

**Comment by ftastisch** [comment]
Thank you for your help. Somehow I did not get it to work, also without rotation touch was not working properly.
So basically I gave up and followed this idea: https://smarttechnotes.com/2020/08/21/raspberry-pi-touchscreen-internet-radio/


/home/pi/.xinitrc created with content
````
session=${1:-lxde}
 
case $session in
    lxde           ) exec startlxde-pi;;
    lxterm         ) exec lxterminal;;
    peppy          ) exec lxterminal -e "cd /home/pi/Peppy; python3 peppy.py";;
esac (or your username instead of pi in the last line)
````

.bashrc --> add this at the end
````
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        echo "SSH session, not starting X server."
else
        startx ~/.xinitrc peppy
fi
````
