### ISSUE TITLE
Please help. Peppy Player not starting. (Using DFRobot 7" Touchscreen Display)

### ISSUE THREAD

**Issue by Techposts** [project-owner/Peppy.doc#18]
Receiving the following error

![image](https://user-images.githubusercontent.com/28442414/236897566-00747fe7-43ad-48fb-81ab-e1047e7cc18a.png)

I have edited the resolution in peppy/config.txt

**Comment by Techposts** [comment]
This is the rror I am getting while installing the library

![image](https://user-images.githubusercontent.com/28442414/236899868-f339b3a2-b0d9-4e8c-8c98-18d7bb215206.png)

**Comment by project-owner** [comment]
Hi,

Which OS and Python version do you use? There is the issue in pynanosvg and Python 3.9:
https://forums.raspberrypi.com/viewtopic.php?t=139983&start=300#p1979222
https://github.com/project-owner/Peppy.doc/wiki/Expert
Please try to use Python 3.7 if possible.

Best regards

**Comment by project-owner** [comment]
The new player versions don't use pynanosvg anymore.
