### ISSUE TITLE
openvt: Operation not permitted

### ISSUE THREAD

**Issue by DrTron** [project-owner/Peppy.doc#19]
Hello!

I'm currently trying to upgrade Peppy (was still on Cezanne) and updated the system along with it. It's still Raspberry OS, but based on Bullseye now.

Starting Peppy, I get:
`pi@raspi2:~/Peppy $ openvt -s -w -- python3 peppy.py`
`openvt: Couldn't activate vt 4: Operation not permitted`

So it seems to be some permission issue. I've changed the udev-default-Rule for the tty and rebooted.
Python3 version is 3.7.3

Anything I may have missed?

Thanks!

**Comment by project-owner** [comment]
Hi,

Right after the Cezanne version the player can be started as a service. If you don't use a disk image you can configure it yourself by following these steps:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Headless#configure-player-as-a-service

Best regards

**Comment by DrTron** [comment]
Yes, if you recall I was the one suggesting that and providing the service file ;-)

However, the error stays the same, whether started from the shell or via systemd.
Somehow the virtual terminal needs some permissions the "pi" user doesn't have (or can't be passed on by a ssh-root-shell).
Maybe I'll change the user in the systemd file to root to see what happens...

**Comment by project-owner** [comment]
Oops, now I remember :)
I'm not sure what is the root cause for that issue. I still use Buster OS. It doesn't have such surprises. I'll try to upgrade OS and all other stuff after the next release (June).
I'm afraid if you switch to 'root' you need to reinstall Python libraries as they are specific for the user.

**Comment by DrTron** [comment]
No problem :-)
Since my other Raspi's and Debian systems are on Bullseye, it sounded like a good idea. Bullseye has been out a while now (almost two years), but I may have to write a backup to the sd-card and not touch it again for a while.

That said, "bookworm", or Debian 12, has a release date in June...

**Comment by project-owner** [comment]
OK, when you pull new Peppy version from GitHUb don't forget to install new libraries.
https://github.com/project-owner/PeppyPlayers.doc/wiki/Headless#installing-peppy-player-dependencies
I think after Cezanne you need:
```
pip3 install youtube-dl==2020.12.2
pip3 install pafy
pip3 install numpy -U
pip3 install psutil
pip3 install yahooquery
pip3 install pyaztro
```
The purpose for each of them can be found here:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Headless#disk-image-content

Best regards

**Comment by DrTron** [comment]
Thanks for the heads-up.
I really think pip3 is missing some kind of update-function...

**Comment by DrTron** [comment]
Ok, different error message, same problem.
I'm back on Buster (packages not updated except the python packages you mentioned earlier).

Cezanne runs fine, but Marc fails to start with this:
`openvt: ioctl(VT_ACTIVATE): Operation not permitted`
TBH, I haven't found much about this error.

Can't be _that_ hard to update this thing without brute-force flashing a new image...

**Comment by project-owner** [comment]
Hmm, weird. You can have Cezanne and Marc editions side by side. For example, move Peppy folder with Cezanne to Peppy.bak, pull Marc edition to Peppy folder and see if you have that error only with Marc edition.

I can't think of any difference between editions which could cause that error...

**Comment by project-owner** [comment]
I'll try to install Cezanee and make in-place upgrade (pull Marc from GitHub) either today or tomorrow.

**Comment by DrTron** [comment]
> For example, move Peppy folder with Cezanne to Peppy.bak, pull Marc edition to Peppy folder and see if you have that error only with Marc edition.

That's exactly what I did. Plus updating the python libraries, but they don't seem to interfere with Cezanne, so I don't think that's it.

And thanks for following up on this!

**Comment by project-owner** [comment]
OK, here is what I did:
- installed Cezanne image for Waveshare 3.5" touchscreen
- killed player process
- installed libraries (numpy took long time to install):
```
pip3 install numpy -U
pip3 install psutil
pip3 install pyaztro
```
- moved Peppy folder to Peppy.bak
- pulled the latest Marc edition from GitHub
- rebooted
Everything worked fine after reboot.

Then I disabled start on boot at /etc/rc.local and rebooted again and ran the commands:
```
pi@raspberrypi:~ $ cd Peppy
pi@raspberrypi:~/Peppy $ openvt -s -w -- python3 peppy.py
In another terminal:
pi@raspberrypi:~ $ ps -elf|grep python
0 S pi        1103   874  0  80   0 -  1611 do_wai 02:03 pts/0    00:00:00 openvt -s -w -- python3 peppy.py
0 D pi        1104  1103 28  80   0 - 20082 generi 02:03 tty2     00:00:01 python3 peppy.py
0 S pi        1132  1004  0  80   0 -  1837 pipe_r 02:03 pts/1    00:00:00 grep --color=auto python
```
Peppy started as well after pressing Ctrl-C the player was still running:
```
pi@raspberrypi:~/Peppy $ openvt -s -w -- python3 peppy.py
^C
pi@raspberrypi:~ $ ps -elf|grep python
0 S pi        1104     1  5  80   0 - 45822 hrtime 02:03 tty2     00:00:07 python3 peppy.py
0 S pi        1698  1004  0  80   0 -  1837 pipe_r 02:05 pts/1    00:00:00 grep --color=auto python
```
Player was still running.
So, I cannot reproduce the issue.

**Comment by DrTron** [comment]
Hmm, the fact that openvt has an issue opening a tty does point it towards an issue with the screen some how.
I have a DSI screen connected by the flat cable, pretty much the same the "original" screen is, just in a 5" size. Made sense at the time. So I installed the Cezanne image for the official 7"-screen.

The waveshare you have is a HDMI screen?

**Comment by project-owner** [comment]
That was Wvashare 3.5" SPI touchscreen.
You need to install pyaztro, otherwise player doesn't start. I didn't list it as that screensaver doesn't work anymore. I'll fix it in the next release:
https://github.com/project-owner/Peppy.doc/wiki/Horoscope
But without it the player doesn't start.

**Comment by DrTron** [comment]
Got "Marc" working now, it must have been my config.txt file.
I copied the default one and it started up. I've now tweaked the config again to my liking and no issues so far. I did notice a few lines in there that weren't in my Cezanne config file, maybe that was it.
Still, a strange error message. Plus, it still crashes hard when trying to restart Peppy or even on a reboot.

Thanks for the help!

**Comment by project-owner** [comment]
You can fix that crashing by configuring player as a service. When you reboot or shutdown Marc assumes that it shoud stop/restart a service.

**Comment by DrTron** [comment]
I have it running as a systemd-service. Still freezes the whole system, either on stopping the service or on a reboot.

**Comment by project-owner** [comment]
Hmm, nothing in the log file?
If you have experience debugging software, you can try to add more logging messages (e.g. logging.debug("foo")) to the pre-shutdown function to see where it actually fails:
https://github.com/project-owner/Peppy/blob/9f2a9742c667e71c4f64da7391bb17ce703e4145/peppy.py#L2712

**Comment by DrTron** [comment]
Thanks, I'll enable logging and see if that turns up anything (currently still disabled by default) and maybe add a few logfile lines into the code.

**Comment by project-owner** [comment]
OK, I've just installed service file and tested both Reboot and Shutdown from a Web Configuration UI. Both worked fine.

**Comment by project-owner** [comment]
Please reopen if the issue is still there.
