### ISSUE TITLE
Peppy player won't start, Import Error, no module named config

### ISSUE THREAD

**Issue by BBHydraOC** [project-owner/Peppy.doc#20]
My peppy player started having some issues, I tried updating to the latest version, but my backup of Kandinsky won't work anymore. I'm just running python peppy.py and it errors out, autolaunch doesn't work either

**Comment by project-owner** [comment]
Hi, please clarify how did you update to the latest Malevich version? The best way is to use the disk image which has all dependencies pre-installed. How did you make a backup?

**Comment by BBHydraOC** [comment]
I used the git command to do it after using the cp command to copy the folder to a backup folder. There isn't a disk image for the 3.5" tft display I use for Malevich

**Comment by project-owner** [comment]
That's right, unfortunately there are no disk images with Malevich Edition for SPI displays. I spent a lot of time trying to make it working with a new OS version (Bookworm), new Python version and new Pygame version. I was not able to do that. Hopefully that will be fixed in the future.

Right now, you can just install the previous disk image with Kandinsky Edition. If you changed any files just copy them to you desktop/laptop, install Kandinsky disk image and then copy those files back to Pi.

**Comment by BBHydraOC** [comment]
I flashed the kandinsky edition to my sd card, but now the colors are all wrong, the UI is pink instead of blue

**Comment by project-owner** [comment]
How did it work before? Which display do you have and which disk image did you use before?

**Comment by BBHydraOC** [comment]
I manually installed it before with commands on top of regular raspbian, I'm using a 3.5" GPIO display

**Comment by project-owner** [comment]
More likely you need to install a correct driver for your display. Which driver did you install before?

**Comment by BBHydraOC** [comment]
I used the driver on LCD wiki for my display, how do I switch the drivers in the premade OS image?
http://www.lcdwiki.com/3.5inch_RPi_Display

**Comment by project-owner** [comment]
Just follow the instructions on that page for your display:
```
sudo rm -rf LCD-show
git clone https://github.com/goodtft/LCD-show.git
chmod -R 755 LCD-show
cd LCD-show/
sudo ./LCD35-show
```

**Comment by BBHydraOC** [comment]
Following those instructions just displays a white screen, as if it is not giving any signal to the display.

**Comment by BBHydraOC** [comment]
The pi won't boot up anymore

**Comment by project-owner** [comment]
Login to Pi and check the file /etc/rc.local and comment out or delete the line with 'fbcp' if it's there. Then reboot.

**Comment by BBHydraOC** [comment]
There is nothing with 'fbcp' in /etc/rc.local

**Comment by project-owner** [comment]
What is a content of the file /boot/config.txt ?

**Comment by BBHydraOC** [comment]
# For more options and information see
# http://www.raspberrypi.org/documentation/configuration/config-txt.md
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on
enable_uart=1
# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
dtoverlay=waveshare35b
#dtoverlay=ads7846,cs=1,penirq=17,penirq_pull=2,speed=1000000,keep_vref_on=1,swapxy=1,pmax=255,xohms=60,xmin=200,xmax=3900,ymin=200,ymax=3900
hdmi_force_hotplug=1
#max_usb_current=1
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 480 320 60 6 0 0 0
hdmi_drive=2
display_rotate=0

**Comment by BBHydraOC** [comment]
[config.txt](https://github.com/project-owner/Peppy.doc/files/14969630/config.txt)

**Comment by BBHydraOC** [comment]
It looks like the colors on the display are inverted for some reason as the issue

**Comment by project-owner** [comment]
Hmm, according to this driver installation script for your display:
https://github.com/goodtft/LCD-show/blob/0c296dde46de6b35174b55bfcfe64279caf72451/LCD35-show#L27
the driver name is tft35a, but in the file /boot/config.txt there is waveshare35b which is not for your display.

**Comment by project-owner** [comment]
Do you have this file? /boot/overlays/tft35a.dtbo

**Comment by BBHydraOC** [comment]
The drive got corrupted somehow, I've gotta start all over

**Comment by BBHydraOC** [comment]
yes that file is there

**Comment by project-owner** [comment]
OK, just to confirm:
- Malevich disk image is in use
- LCD35-show script for display was executed
- The driver file tft35a.dtbo is in folder /boot/overlays
- The file /boot/config.txt contains the following lines after running the script LCD35-show:
```
hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1
dtoverlay=tft35a:rotate=90
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 480 320 60 6 0 0 0
hdmi_drive=2
```
- The line 'dtoverlay=waveshare35b' in file /boot/config.txt which comes with disk image was commented out or deleted

**Comment by project-owner** [comment]
My bad, it should be Knadinsky disk image

**Comment by BBHydraOC** [comment]
yeah it looks exactly the same

**Comment by BBHydraOC** [comment]
Is there a way to just invert the colors on the premade image? That's what it looks like it's doing anyways with the included driver

**Comment by project-owner** [comment]
Usually it's the problem with wrong driver:
https://forum-raspberrypi.de/forum/thread/38115-peppy-webradio/?postID=362549#post362549
https://github.com/project-owner/Peppy/issues/8

or just google for 'peppy player inverted colors'

**Comment by project-owner** [comment]
The player doesn't use the file /etc/rc.local for starting the player anymore. The player starts as a service now.

**Comment by BBHydraOC** [comment]
I got the colors back to normal by installing the waveshare35a overlay file

**Comment by project-owner** [comment]
Great!
