### ISSUE TITLE
Encoders issue - request for help

### ISSUE THREAD

**Issue by PetrSyk** [project-owner/Peppy.doc#21]
I have problem with encoders. They doesn't work. Only one of then do something but wrong. When I turn with him one step the player is muted. Next steps unmuted it and so on again. Nothing else. Turn off/on on web ui doesnt have any effect - still the same. I also checked config.txt. My configuration Rpi3, gpio extpansion board, hifiberry mini amp, Miro. Please could anybody give me advice? Any Idea. Thanks

**Comment by project-owner** [comment]
Hi, 

Please run the following commands in a terminal with Pi connected to the Internet:
```
sudo apt-get remove python3-RPi.GPIO
sudo apt-get install python3-rpi-lgpio
```
This is described here:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Known-Issues

Regards

**Comment by PetrSyk** [comment]
Thanks for the advice, I used it and it's better. Could you please clarify something for me please? The volume encoder works up and down but over one step. One step sound, second silent. Is it that correct? Thank you.

**Comment by project-owner** [comment]
I cannot reproduce the issue which you described. Please make sure that you correctly connected a rotary encoder pins:
https://github.com/project-owner/Peppy.doc/wiki/Rotary-Encoders

**Comment by project-owner** [comment]
Hi, the connection looks OK to me. Please make sure that MiniAmp doesn't use pins used by encoder. 

After switching to the new library 'rpi-lgpio' the encoders are not so stable anymore. I need to investigate if any software changes should be done to stabilize it. With the old library (RPi.GPIO) encoders were more stable. If you don't need any new features in the player you can try one of the previous disk images (e.g. [Kandinsky Edition](https://github.com/project-owner/PeppyPlayers.doc/wiki/Disk-Images)) to see if the encoder works better there.

**Comment by PetrSyk** [comment]
Yes there is a conflict
HIFIBERRY MINIAMP
GPIOs 18-21 (pins 12, 35, 38 and 40) are used for the sound interface. GPIO16 can be used to mute the power stage. GPIO26 shuts down the power stage. You can’t use these GPIOs for any other purpose.

**Comment by project-owner** [comment]
You can assign different pins to encoders:
https://raw.githubusercontent.com/project-owner/Peppy.doc/master/images/software/re-config.png

**Comment by PetrSyk** [comment]
I changed connections to free pins
Up 16->5
Down 26->6
Mute 13->13

Left 6->22
Right 12->23
Select 5->27
Save&Reboot

Only mute is working correctly. Volume up or down nothing. Selections sometimes something.

**Comment by project-owner** [comment]
Hmm, weird. For me it works with the original assignment (16, 26, 13) but doesn't work (except Mute) with your assignment (5, 6, 13). I'll try to debug during the coming weekend.

**Comment by project-owner** [comment]
Hmm, weird. For me it works with the original assignment (16, 26, 13) but doesn't work (except Mute) with your assignment (5, 6, 13). Instead of the Volume Up/Down it works as Move Right. I'll try to debug during the coming weekend.

**Comment by project-owner** [comment]
It looks like my diagram on this page was wrong: https://github.com/project-owner/Peppy.doc/wiki/Rotary-Encoders
Pin GPIO6 is actually pin 31 and GPIO12 is pin 32. So, if you switch to the following pins it should work:
Up 16->5 (pin 29 on connector)
Down 26->12 (pin 32 on connector)
Mute 13->13

**Comment by PetrSyk** [comment]
Unfortunately I am still not fully successful.  Mute and select works. Others not.
![IMG_2195](https://github.com/user-attachments/assets/4485114c-0743-410b-9041-7813d5a68449)
![IMG_2198](https://github.com/user-attachments/assets/5f3d871a-ac82-4797-a04e-4eb9e57ebcbe)

**Comment by project-owner** [comment]
I've double checked, pins 5, 12, 13 work for me. There is just one issue related to the Mute - it automatically switches on. I need to investigate why that happens.

Please check that you correctly connected pins on the 'even' side of the connector. Also I'd recommend to disconnect the second encoder just for testing. And finally check that there is nothing selected in the GPIO sections 'Player Buttons' and 'Menu Buttons'. If it still doesn't work disconnect all boards from Pi and leave only one encoder connected.

**Comment by PetrSyk** [comment]
I found a fault on the board. It already works. Thank you for your support and patience.
