### ISSUE TITLE
Peppy not in full screen and trouble with calibration 

### ISSUE THREAD

**Issue by Enadeia** [project-owner/Peppy.doc#3]
Hello,

I installed my raspberry following all the steps and everything is perfect, until I launch Peppy:

- it is displayed in a square smaller than the screen, so it isn't in full screen
- the touchscreen seems to be "inverted": when I touch a button on Peppy it has no effect but it sometimes activate another button. I could notice that I could slide the volume bar by touching the screen from up to bottom on the left side of the screen, instead of from left to right on the bottom of the screen as expected.

I can't figure out what is wrong, because I installed exactly the same raspbian distribution and followed all the steps as described, the touchscreen worked fine and was well calibrated until I installed and launched Peppy.

I also have no sound playing. When I did the test "speaker-test -Dhw -c2 -tsine -f200" I could hear the speakers working fine. I might have a problem with the config.txt file, because I didn't exactly know what to do with:
The following example shows parameters which should be added to the audio section of the config.txt file in order to use mpd on Linux platform:

**[audio]
server.folder = /usr/bin
server.command = mpd
client.name = mpdsocket
music.folder = /music**

As I had not such text in my config.txt file, so I added 
**server.command = mplayer -af volnorm=2:0.75 -idle -slave -quiet -msglevel statusline=6 -msglevel global=6
client.name = mplayer
music.folder =**

For mplayer. So my config.txt file contains:

**# --- added by Nadia on 03th october

dtoverlay=hifiberry-amp

[audio]
server.folder = /usr/bin

server.command = mpd
client.name = mpdsocket
music.folder = /var/lib/mpd/music

server.command = mplayer -af volnorm=2:0.75 -idle -slave -quiet -msglevel statu$
client.name = mplayer
music.folder =**

Maybe I misunderstood what to do with the [audio] section ?

**Comment by project-owner** [comment]
Congrats! You went a long way already :)
1. What is the resolution of your touchscreen? The resolution of Peppy screen can be adjusted in file config.txt. Set width and height settings to the size of your touchscreen.
2. Which Raspbian distribution have you installed?
3. More likely misbehavior with actions on touchscreen caused by the issue described here:
https://github.com/project-owner/Peppy.doc/wiki/Pygame
Did you follow the steps described there ?
4. Which audio player have you installed? Is it mpd, mplayer or vlc? You need just one of them. First decide which player you would like to use. You can see functionality available from each player in Pappy in corresponding wiki page for that player. My recommendation is VLC as it's much easier to use. Just let me know what are you planning to use. That will define the content of players.txt file.

**Comment by project-owner** [comment]
When I'm talking about config.txt I mean the file under Peppy player folder. For example if you installed Peppy in folder /home/pi/Peppy/ then the file is /home/pi/Peppy/config.txt

**Comment by Enadeia** [comment]
Oh OK I was using the /boot/config.txt...

2017-10-31 19:35 GMT+01:00 project-owner <notifications@github.com>:

**Comment by project-owner** [comment]
Please let me know if after following steps 1, 2, 3 described above UI works fine in touchscreen. After that we can focus on audio.

**Comment by Enadeia** [comment]
*Thanks, I am glad I could reach this step, thanks for helping too !*
*My answers to your questions ->*
*1- I have a **3.5" adafruit display with 480x320. I adjusted it and it
works fine now.*
*2- I installed 2015-09-24-raspbian-jessie-pitft35r*
*3- I already did the steps described here *https://github.com/project-
owner/Peppy.doc/wiki/Pygame
*4- I thought I had to install the 3 of them so that is what I did. I am
now planning to use VLC.*

2017-10-31 18:12 GMT+01:00 project-owner <notifications@github.com>:

**Comment by Enadeia** [comment]
I forgot to mention : the display works fine in full screen now but not the touch screen, it's still inverted...

**Comment by Enadeia** [comment]
I have the following errors in /var/log/syslog if it can help:

BCM2708-dmaengine 20007000.dma: failed to get irq dor DMA channel 13
systemd-udevd(165): failed to execute 'lib/udev/mtp-probe' 'mtp-probe /sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.1 1 3': No such file or directory
snd-hifiberry-amp sound: snd_soc_register_card() failed: -517
wpa_supplicant(393): wlan0: Failed to initialize driver interface (if this is related to WIFI it is ok as I don't wan't to use wifi, only ethernet)
networking(208): Failed to bring up wlan0
wpa_supplicant(421): wlan1: Failed to initialize driver interface
networking(208): Failed to bring up wlan1
system(465): Failed at step EXEC spawning /etc/rc.local: Exec format error
systemd(1): Failed to start /etc/rc.local Compatibility
systemd(1): Unit rc-local.service entered failed state

**Comment by project-owner** [comment]
Please cleanup file /boot/config.txt - remove all new lines which you added there.
Let's assume that step #3 was successful. Then the only thing which can cause the issue which you mentioned is 'rotate' setting for touchscreen driver in file /boot/config.txt. Here is what I have at the
bottom of that file:
dtoverlay=pitft35r,rotate=90,speed=42000000,fps=20
If you have different setting just set it to 90. If you have 90 try to set it to 0, 180, 270. All this explained here:
https://learn.adafruit.com/adafruit-pitft-3-dot-5-touch-screen-for-raspberry-pi/faq?view=all

I believe you installed VLC player and VLC Python binding before. If so you have to set
player.name = vlc
in audio section of the /home/pi/Peppy/players.txt file. This is the only change you need to make
in Peppy player to use VLC.

Have you installed HifiBerry Amp? If so please follow the steps described here:
https://github.com/project-owner/Peppy.doc/wiki/HiFiBerry-Amp

**Comment by Enadeia** [comment]
I changed player to mpd and the sound is working fine now. I can manage
Peppy player thru Peppy web UI.

But, I still have troubles with the touchscreen : the display works just
fine but when I press somewhere on the screen it is as if the resistive
film was set in portrait.

In the /boot/config.txt I have :
dtoverlay=pitft35r,rotate=270,speed=42000000,fps=20

rotate 270 because I had to turn the screen upside down. It works fine for
the display but not the touchscreen...

2017-11-02 4:10 GMT+01:00 project-owner <notifications@github.com>:

**Comment by project-owner** [comment]
When you install mpd it runs as a service and doesn't allow any other player to use audio system.
If you want you can disable mpd service and start using vlc. But if you are planning to use Peppy
only for radio functionality mpd should be OK.  Only if you would like to play files I would
recommend to use vlc instead of mpd.

Have you tried to set rotate=90 ? I think the touchscreen will work only with this setting. Do
you need 270 because you have to mount player in enclosure in special position?

**Comment by Enadeia** [comment]
For the moment I just planned to play radios.
I tried 3 times to reinstall the whole system with VLC and I am giving up for now. The sound is working fine with mpd so I will see later for VLC.

When my screen was on 90 until last day I had the same touchscreen trouble... I can't understand

Nadia

De : project-owner
Envoyé : vendredi 3 novembre à 21:53
Objet : Re: [project-owner/Peppy.doc] Peppy not in full screen and trouble with calibration (#3)
À : project-owner/Peppy.doc
Cc : Enadeia, Author

When you install mpd it runs as a service and doesn't allow any other player to use audio system.
If you want you can disable mpd service and start using vlc. But if you are planning to use Peppy
only for radio functionality mpd should be OK. Only if you would like to play files I would
recommend to use vlc instead of mpd.

Have you tried to set rotate=90 ? I think the touchscreen will work only with this setting. Do
you need 270 because you have to mount player in enclosure in special position?

**Comment by project-owner** [comment]
rotate=90 should be OK. I just suspect that step #3 was not successful because of some reason.
Have you tried to calibrate after rotation?

**Comment by Enadeia** [comment]
Hi, I have been trying over and over but could not fix it.
I tried to recalibrate manually after rotation, when I launch startx the pointer appears exactly under my stylet. But when I launch Peppy, the pointer appears inverted, I mean left instead of right AND top instead of bottom.
I tried to reset everything to 90, recalibrated, launched Peppy, and I still have a weird behavior, the pointer doesn't click where I would like to.
My screen is this one:
https://www.adafruit.com/product/2441
I am stucked :/

**Comment by project-owner** [comment]
I'll try to repeat the whole installation from scratch and see if I'll face the same issue.

**Comment by Enadeia** [comment]
OK I'll try this, I was sharing the same idea. I'll keep you informed. Thanks !

Nadia

________________________________

**Comment by project-owner** [comment]
Please set the following property in /home/piPeppy/config.txt to True and let me know if that fixes the issue:
use.mouse = True

**Comment by project-owner** [comment]
I was able to configure everything from scratch and it's working fine (including vlc). If you still have issues I can prepare new wiki page - 'Quick Installation Guide' and list in details all steps required to make system working. That will take a day or two to prepare such page. Please let me know if you need it.

**Comment by project-owner** [comment]
I modified wiki page about Pygame:
https://github.com/project-owner/Peppy.doc/wiki/Pygame
that should help to update SDL and fix touchscreen issue.
I'm still working on step by step guide.

**Comment by Enadeia** [comment]
OK I am reinstalling the whole project too. Thanks for your updates, and
yes, a quick installation guide could help me, it would be very nice of you
if you could write this !
I'll keep you informed.

2017-11-08 6:47 GMT+01:00 project-owner <notifications@github.com>:

**Comment by project-owner** [comment]
I completed the guide:
https://github.com/project-owner/Peppy.doc/wiki/Installation-Guide
if you follow all steps you should be able to run the system. I'll update other wiki pages later on.
It would be great to distribute SD Card images but I don't know where I could host so large files (GBs). GitHub doesn't allow to host such big files.

**Comment by Enadeia** [comment]
I was thinking about posting an image file too. Could be hosted somewhere
else with a link on github ?
Thanks a lot for the installation guide, I will check it right now :)
The good news is : I reinstalled the whole system and the screen and touch
area are working fine ! It's a really nice UI. But no sound is coming, the
speakers are working as I can hear the test
speaker-test -Dhw -c2 -tsine -f200
The console says :
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM hifiberry

2017-11-08 20:07 GMT+01:00 project-owner <notifications@github.com>:

**Comment by project-owner** [comment]
That happens because VLC was not properly configured (I hope you use VLC). Please check section 'Install Peppy Player' of the guide in particular instructions about VLC configuration (I hope you use VLC).

**Comment by Enadeia** [comment]
Yes I am on this section of the documentation.
I use VLC and in /home/pi/Peppy/players.txt I have

[vlc.linux]

server.command = --aout=alsa --alsa-audio-device=hifiberry --verbose=-1


I dont get exactly what I have to change ? Replace hifiberry with hw ?

2017-11-08 20:32 GMT+01:00 project-owner <notifications@github.com>:

**Comment by project-owner** [comment]
If you see hw after running aplay -L then yes you have to replace hifiberry by hw

**Comment by Enadeia** [comment]
OH YES IT WOOOOOORKS !!!
😂

2017-11-08 20:35 GMT+01:00 project-owner <notifications@github.com>:

**Comment by project-owner** [comment]
Congratulations! It was a long way... :)

**Comment by project-owner** [comment]
If you have any other questions you can send e-mail. My address is available in all Python source files.

**Comment by Enadeia** [comment]
OK, thanks a lot for your helpful advises ! First thing I a going to do is
to save an IMG of my SDCARD :-) and then I will have to find out how to
open a *.py file to seek for your email address :D

2017-11-08 20:41 GMT+01:00 project-owner <notifications@github.com>:

**Comment by project-owner** [comment]
All source files are here on github:
https://github.com/project-owner/Peppy
just open any of them in browser.
If you think we resolved your issue, please close it. Thanks!

**Comment by Enadeia** [comment]
Many thanks for your help ! 
I am closing the issue.

**Comment by project-owner** [comment]
@Enadeia I'm planning to create new wiki page with Peppy projects which other people created. If you don't mind please send me image(s) with your project. Please reply by e-mail. Thanks!

**Comment by Enadeia** [comment]
Hi, OK I'll take some pictures and send it to you.

Have a nice Day

Nadia

De : project-owner
Envoyé : dimanche 10 décembre à 20:23
Objet : Re: [project-owner/Peppy.doc] Peppy not in full screen and trouble with calibration (#3)
À : project-owner/Peppy.doc
Cc : Enadeia, Mention

@Enadeia<https://github.com/enadeia> I'm planning to create new wiki page with Peppy projects which other people created. If you don't mind please send me image(s) with your project. Please reply by e-mail. Thanks!

**Comment by Enadeia** [comment]
Hi,

You will find attached pictures of our project. We called it Siam's Music
Box. We made it with my 3 teenagered boys (13, 12 and 10) who act like
siamese as they always do everything stuck to each other 😄 and my husband
helped a bit too.

Speakers are external. I didn't use the remonte control ability. For the
moment we found a box at IKEA made with carboard which perfectly fits to
our project and was easy to cut. Next step would be to create our own
aluminium case. We might do it in 2018 ^^

Tell me if you need more explanations ! Thanks for sharing your Peppy
project ☺️

Nadia
[image: Images intégrées 1]

**Comment by Enadeia** [comment]
[image: Images intégrées 1]

2017-12-10 20:23 GMT+01:00 project-owner <notifications@github.com>:

**Comment by project-owner** [comment]
Nadia, this 'issues' page doesn't support images. Please send them to my e-mail peppy.player@gmail.com
If you don't mind I can mention your name and country. Please let me know what I should write about project creator(s).
