### ISSUE TITLE
Incorrect splash page wget service 

### ISSUE THREAD

**Issue by dumbo25** [project-owner/Peppy.doc#4]
I am trying to get this to work and I am following the expert install.

On this page, https://github.com/project-owner/Peppy.doc/wiki/Expert

For this instruction:

Download service file for splash screen:

wget https://github.com/project-owner/Peppy.doc/blob/master/files/splash.service

The above should point to the raw file as shown below. Otherwise, the page is downloaded and the enable fails.

https://raw.githubusercontent.com/project-owner/Peppy.doc/master/files/splash.service

**Comment by project-owner** [comment]
Thanks for pointing to the issue. I've changed the link on wiki.
