### ISSUE TITLE
Markdown doesn't render correctly on GitHub

### ISSUE THREAD

**Issue by linusg** [project-owner/Peppy.doc#5]
I'm not sure if this is intentional or not, but most if not all of the documentation Markdown documents don't render correctly on GitHub:

![image](https://user-images.githubusercontent.com/19366641/51670528-1d2dbb00-1fc7-11e9-87cf-6fc04ffbe7e8.png)

Should it be converted to [GitHub Flavored Markdown](https://github.github.com/gfm/) (GFM)?

- Image URLs have to be changed:

  - https://github.com/project-owner/Peppy.doc/blob/master/images/software/about.png returns an **HTML page** (the GitHub interface) with the **image preview**
  - https://raw.githubusercontent.com/project-owner/Peppy.doc/master/images/software/about.png returns the **plain image**
- Spaces in link URLs must be URL-encoded:
    ```
    ![Home Screen](https://github.com/project-owner/Peppy.doc/wiki/Home Screen)
    ![Home Screen](https://github.com/project-owner/Peppy.doc/wiki/Home%20Screen)
    ```
- Markdown in HTML must be separated by an empty line:
    ```
    <p align="center">

    ![about](https://raw.githubusercontent.com/project-owner/Peppy.doc/master/images/software/about.png)
    </p>
    ```
    Edit: apparently the center-aligning doesn't work then, so more HTML:
    ```
    <p align="center">
      <img src="https://raw.githubusercontent.com/project-owner/Peppy.doc/master/images/software/about.png" alt="about">
    </p>
    ```

So this:

---
```
The About screen consists of the application name, application logo and version name. The screen will be displayed after clicking 'About' button on the [Home screen](https://github.com/project-owner/Peppy.doc/wiki/Home Screen).
<p align="center">
[[https://github.com/project-owner/Peppy.doc/blob/master/images/software/about.png|alt=about]]
</p>

[<<Previous](https://github.com/project-owner/Peppy.doc/wiki/Peppy Player UI) | [Next>>](https://github.com/project-owner/Peppy.doc/wiki/Home Screen)
```

The About screen consists of the application name, application logo and version name. The screen will be displayed after clicking 'About' button on the [Home screen](https://github.com/project-owner/Peppy.doc/wiki/Home Screen).
<p align="center">
[[https://github.com/project-owner/Peppy.doc/blob/master/images/software/about.png|alt=about]]
</p>

[<<Previous](https://github.com/project-owner/Peppy.doc/wiki/Peppy Player UI) | [Next>>](https://github.com/project-owner/Peppy.doc/wiki/Home Screen)

---

would become

---
```
The About screen consists of the application name, application logo and version name. The screen will be displayed after clicking 'About' button on the [Home screen](https://github.com/project-owner/Peppy.doc/wiki/Home%20Screen).
<p align="center">
  <img src="https://raw.githubusercontent.com/project-owner/Peppy.doc/master/images/software/about.png" alt="about">
</p>

[<<Previous](https://github.com/project-owner/Peppy.doc/wiki/Peppy%20Player%20UI) | [Next>>](https://github.com/project-owner/Peppy.doc/wiki/Home%20Screen)
```

The About screen consists of the application name, application logo and version name. The screen will be displayed after clicking 'About' button on the [Home screen](https://github.com/project-owner/Peppy.doc/wiki/Home%20Screen).
<p align="center">
  <img src="https://raw.githubusercontent.com/project-owner/Peppy.doc/master/images/software/about.png" alt="about">
</p>

[<<Previous](https://github.com/project-owner/Peppy.doc/wiki/Peppy%20Player%20UI) | [Next>>](https://github.com/project-owner/Peppy.doc/wiki/Home%20Screen)

---

**Comment by project-owner** [comment]
This is weird, here is what I see in Chrome and Firefox

[image: image.png]

**Comment by linusg** [comment]
I'm on the latest Chromium and Firefox, the issue shouldn't depend on the browser though, as the Markdown is rendered to HTML on the server side.

BTW I don't see your image either:

![image](https://user-images.githubusercontent.com/19366641/51691662-7f081800-1ffb-11e9-82a8-ae42adfa7015.png)

**Comment by project-owner** [comment]
![image](https://user-images.githubusercontent.com/16547956/51693319-93c0bd80-1fb3-11e9-8b0b-bd0fcffff3cf.png)

**Comment by linusg** [comment]
That's a different page though! I'm not talking about the wiki but all the files here: https://github.com/project-owner/Peppy.doc

E.g. https://github.com/project-owner/Peppy.doc/About.md

**Comment by project-owner** [comment]
aah, I have never paid attention to the direct links. I suppose that it's always accessed through wiki :)

**Comment by project-owner** [comment]
Removed the files and added the link to the wiki pages
