### ISSUE TITLE
Spotify Connect: Web interace freeze

### ISSUE THREAD

**Issue by jimmyjules** [project-owner/Peppy.doc#6]
I use Peppy Headless (Constable) image downloaded on 27 Nov 20. 
When i push "Spotify Connect" on web interface the interface will freeze permanently until I reboot. 
Spotify connect will still work. Also ssh access on the machine works.

**Comment by jimmyjules** [comment]
. I found the UI is indeed still responsive.

**Comment by project-owner** [comment]
I like the issues which are closed before I was able to read it :) Feel free to reopen if you are still facing the issue.

**Comment by jimmyjules** [comment]
I tested further.  When I push it the symbol in the UI will change color. There is no sub-menu  for Spotify Connect like for other options where I can control volume. Peppy Player can be selected for playback in Spotify app.

It seems playback sometimes starts ok. Other times I will have to adjust the colume with amixer sset. After a while playback may stop and I have to start over again.

**Comment by jimmyjules** [comment]
see above.

**Comment by project-owner** [comment]
You are right, in the Spotify Connect mode you cannot use the playback controls (e.g. volume etc). That's explained at the bottom here:
https://github.com/project-owner/Peppy.doc/wiki/Spotify-Connect

You can enable file logging by setting this property to True:
https://github.com/project-owner/Peppy/blob/d9eb701c1f66be2ef5bccc8457bb96ece0f46f79/config.txt#L30
The log messages will be available in the file: /home/pi/Peppy/peppy.log

Please check the log file for any errors when the playback stops. 

Thanks!
