### ISSUE TITLE
Error message when starting peppy.py

### ISSUE THREAD

**Issue by jimmyjules** [project-owner/Peppy.doc#7]
I have completed the steps under https://github.com/project-owner/Peppy.doc/wiki/Expert. 

The headless client works ok. I control it via web interface.

Now I tried to setup a a fresh image with a Touchscreen (https://joy-it.net/de/products/RB-TFT3.2V2). I've configured it according to waveshare website  (https://www.waveshare.com/wiki/3.2inch_RPi_LCD_(B)).

When booting the PI the splash screen will be displayed but nothing else. Via ssh I can see the following messages when I try to start peppy.py

pi@display:~/Peppy $ python3 peppy.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "peppy.py", line 2318, in <module>
    main()
  File "peppy.py", line 2314, in main
    peppy = Peppy()
  File "peppy.py", line 93, in __init__
    self.util = Util(connected_to_internet)
  File "/home/pi/Peppy/util/util.py", line 133, in __init__
    self.config_class = Config()
  File "/home/pi/Peppy/util/config.py", line 375, in __init__
    self.pygame_screen = self.get_pygame_screen()
  File "/home/pi/Peppy/util/config.py", line 1259, in get_pygame_screen
    pygame.display.init()
pygame.error: Unable to open a console terminal

pi@display:~/Peppy $ sudo python3 peppy.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "peppy.py", line 30, in <module>
    from event.dispatcher import EventDispatcher
  File "/home/pi/Peppy/event/dispatcher.py", line 22, in <module>
    from ui.menu.stationmenu import StationMenu
  File "/home/pi/Peppy/ui/menu/stationmenu.py", line 22, in <module>
    from util.util import IMAGE_SHADOW, IMAGE_SELECTION, FOLDER_ICONS, EXT_PNG, IMAGE_STAR, V_ALIGN_BOTTOM
  File "/home/pi/Peppy/util/util.py", line 32, in <module>
    from util.config import Config, USAGE, USE_VOICE_ASSISTANT, COLORS, COLOR_DARK, FONT_KEY, CURRENT, FILE_LABELS, \
  File "/home/pi/Peppy/util/config.py", line 27, in <module>
    from util.collector import GENRE, ARTIST, ALBUM, TITLE, DATE, TYPE, COMPOSER, FOLDER, FILENAME
  File "/home/pi/Peppy/util/collector.py", line 27, in <module>
    from mutagen import File
ModuleNotFoundError: No module named 'mutagen'

mutagen is installed: 

pi@display:~/Peppy $ pip3 install --user mutagen
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: mutagen in /home/pi/.local/lib/python3.7/site-packages (1.45.1)

**Comment by project-owner** [comment]
Hi,

Please make sure that you start the player using the following command in the ssh session:
`openvt -s -- python3 peppy.py`

BTW, I found some info about joy-it display installation on German forum:
https://forum-raspberrypi.de/forum/thread/38115-peppy-webradio/?postID=418741#post418741
It's very helpful forum.

Best regards

**Comment by jimmyjules** [comment]
Ok I got it now. I used the driver from the waveshare.com website and I also put the parameters in /boot/config,txt. 

After that Peppy player still wouldn't start. It turned out I did not set the correct display dimensions in ~/Peppy/config.txt

Thank you! I will refer to the forum in the future.

**Comment by jimmyjules** [comment]
see above

**Comment by project-owner** [comment]
OK,

Also make sure that you changed the resolution for the VU Meter screensaver for 320x240:
nano Peppy/screensaver/peppymeter/config.txt
screen.size = small

Best regards.
