### ISSUE TITLE
Song Order

### ISSUE THREAD

**Issue by timault** [project-owner/Peppy.doc#8]
First I would love to say I love this project.

That being said, When playing songs from a collection (Album). The songs do not follow the track number, they are always shuffled.

The metadata was set with kid3.

**Comment by project-owner** [comment]
Hi timault,

Thank you for the interest in the player!
Unfortunately I couldn't reproduce the issue. 
For the playback the player is using file names. It plays them in the alphabetical order by default. It doesn't use the metadata.
Do you have any non-ASCII characters in the file names? That could cause wrong file sorting in the player.

Best regards

**Comment by timault** [comment]
Thank you for the reply,The files all have standard ascii characters.Example: 01 - Track AI built Peppy Player on the latest version of Raspbian Buster. I don't know if that is causing an issue.On Jan 15, 2021 9:04 PM, project-owner <notifications@github.com> wrote:
Hi timault,
Thank you for the interest in the player!
Unfortunately I couldn't reproduce the issue.
For the playback the player is using file names. It plays them in the alphabetical order by default. It doesn't use the metadata.
Do you have any non-ASCII characters in the file names? That could cause wrong file sorting in the player.
Best regards

**Comment by project-owner** [comment]
I hope you didn't select  the Shuffle mode from the 'Playback Order' menu:
https://github.com/project-owner/Peppy.doc/wiki/Playback-Order
What happens when you press the 'Next' button? Does it play the next or random track?

Best regards

**Comment by project-owner** [comment]
OK, I was able to reproduce the problem on Pi. Before that I tried to Windows machine. Let me try to find the reason...

**Comment by project-owner** [comment]
I've fixed the issue. You can either grab the whole file fileutil.py or just add two lines:
https://github.com/project-owner/Peppy/blob/30e0e545b57f90e4ed00cf361b35b7434542dc75/util/fileutil.py#L193
My main development platform is Windows. It looks like it returns the folder content sorted already. On Linux you need to sort it explicitly.
Thank you for reporting the issue!

Best regards

**Comment by timault** [comment]
I added those two lines to fileutil.py and it works perfectly now.Thank you for sharing your project, and for the work you have done.As I've said before, I love this project and think it is wonderfully done.On Jan 15, 2021 10:58 PM, project-owner <notifications@github.com> wrote:
I've fixed the issue. You can either grab the whole file fileutil.py or just add two lines:
https://github.com/project-owner/Peppy/blob/30e0e545b57f90e4ed00cf361b35b7434542dc75/util/fileutil.py#L193
My main development platform is Windows. It looks like it returns the folder content sorted already. On Linux you need to sort it explicitly.
Thank you for reporting the issue!
Best regards
