### ISSUE TITLE
Peppy freezes when switching to raspotify

### ISSUE THREAD

**Issue by m0ep43** [project-owner/Peppy.doc#9]
Hey,

first of all: I really like this project! After some days fiddeling around all the different configuration possibilities i finally got it all running as intended (Audio-output via bluetooth, auto-restart if bluetooth-connection is lost, fullscreen on some cheap chinese 800x480 HDMI-touchpanel etc...) and use it as a web-radio, Spotify-connect AP and weather station.

However i met one annoying issue:
The VLC player, which is used by default, gives me some stutters from time to time. After a certain time of playing radio it somehow refuses to play any sound at all until i switch over to another radio station and back to the original one.
Due to this i switched over to mpd today and got the internet radio up and running again (until now without any stutters or connection losses), but encounter a big problem with raspotify: As soon as i click on the "Spotify Connect" button the radio stops and i can play music via Spotify, but the UI freezes completely. Only way to recover from this is killing Peppy and restarting it.
The Peppy player logs give no clue at all, the output on the console shows nothing as well.

Please let me know how i can help in solving this issue, i would really love to use Peppy and convince my spouse that it really is awesome 😄 

Best regards from germany

P.S.: I noticed Peppy still shows up in my Spotify after a reboot and without starting Peppy at all. I can connect and play music, altough the service is reported as loaded & inactive (dead) by sytemctl, but i think this has nothing to do with the crash of Peppy and is more of a raspotify problem...

**Comment by project-owner** [comment]
Hi,

Thank you for the interest in Peppy player!

BTW, do you know that there is very active thread dedicated to the player on German Raspberry Pi forum:
https://forum-raspberrypi.de/forum/thread/38115-peppy-webradio/?pageNo=1

Regarding VLC issue, do you use Pi 3 or 4? Which disk image do you use? The latest Hiroshige, the previous Hokusai or any other? Does it happen on any radio station or some particular station(s)? If it's specific station could you let me know that station? In order to fix the issue first I need to reproduce it.

From where do you stream Spotify? Is it iPhone? If so, did you try to use 'Airplay' mode instead of 'Spotify Connect'? The latter was developed when I had a free trial Spotify account. It's expired. 'Airplay' works without account therefore I can debug it. Also 'Airplay' has more features like album art and playback control.

Best regards

**Comment by m0ep43** [comment]
Hey,

wow, that's a quick response ^^

Yea, i have seen that thread pop up from time to time during all the configuration work, but i thought this issue would be better placed here. If you think they can help me over there as well i will post there too. Thanks for the hint.

I use a Raspberry 4B with a custom image provided with the touch panel. With any other image i couldn't get the touchscreen to work as intendend. I followed the steps to install Peppy from the wiki (expert-mode ofc 😉).

We mostly listened to Rock Antenne, but the issues appeared on other stations as well, so i don't think it is limited to specific stations.

To stream Spotify we use either our Android phones or my Win 10 machine. If it helps you fixing the problem i wouldn't mind sharing my Spotify account with you.

Cheers

**Comment by project-owner** [comment]
It's up to you. You can post your questions over there as well. Though I've never seen any discussion about Airplay and Spotify Connect in that thread.

Do you use Wi-Fi or wired network connection?

Right now I'm trying to fix another issue which is related to the volume level. It was reported in that thread/forum.

Also I need to replace Yahoo Weather API which is used for the Weather screensaver by OpenWeather API as the former one will reach the end-of-life by June 1st. So if you use the Weather screensaver be aware that it can suddenly stop working after June 1st. I hope to make the next release with new weather API around that date.

I'll add the issues which you described to this list:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Known-Issues
Hopefully I'll start working on them when I will fix the current issues mentioned above.
I'll update this issue if I'll have any progress.

Best regards

**Comment by m0ep43** [comment]
I am using Wi-Fi, 5Ghz right next to the router.

Thanks for the heads-up regarding the weather API, i will keep a look out for it.

Have a nice weekend

**Comment by project-owner** [comment]
Hi, please try to change this line:
https://github.com/project-owner/Peppy/blob/9be7586e6ae674b5fa2d3afbfbf811319bd38ede/peppy.py#L1747
to:
```
if hasattr(self.player, "proxy") and self.player.proxy.stop_command:
```
and let me know if it will fix the issue.

Best regards

**Comment by m0ep43** [comment]
Hey,

i altered the line and now i can change to the "Spotify Connect"-screen. However going back to the radio now sometimes freezes the UI similar as before. If it does not freeze the UI the player just kills itself and gives a "pygame 1.9.4.post1", similar to the message during start up, in the console.

I've read somewhere else that the stuttering issue might be caused by using both Wi-Fi and bluetooth, so i see where you want to go. I will try it asap, but it might take 2-3 days, quite busy remodeling my working space...

Thanks for your support!

**Comment by project-owner** [comment]
OK, it looks like one more line should be changed for the same issue:
https://github.com/project-owner/Peppy/blob/9be7586e6ae674b5fa2d3afbfbf811319bd38ede/peppy.py#L282
to:
```
if hasattr(self.player, "proxy"):
```
Thank you!

**Comment by m0ep43** [comment]
Great, now i can change between radio and Spotify Connect without any freezes of the UI. Thank you very much!

I hope i can get to trying out the wired internet connection tomorrow.

**Comment by m0ep43** [comment]
Okay, so i tried the wired connection with a disabled Wi-Fi interface (via /boot/config.txt) yesterday and today. The stutter issue seems to be better (not fully resolved), but it still stops the playback after some time. I think this might be caused by the bluetooth connection rather than by Peppy.

If you want to you might close this issue, since there seem to be no more problems from Peppys side.

Thank you very, very much for your quick help 😁
